# 设置content为分词索引

PUT http://localhost:9200/index/_mapping
Content-Type: application/json

{
  "properties": {
    "content": {
      "type": "text",
      "fields": {
        "keyword": {
          "type": "keyword"
        }
      }
    }
  }
}

###
